lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 10800
  token_extractors:
    authorization_header:
      enabled: true
      prefix: Bearer
      name: Authorization
    cookie:
      enabled: true
      name: BEARER
    split_cookie:
      enabled: true
      cookies:
        - jwt_hp
        - jwt_s
  set_cookies:
    jwt_hp:
      lifetime: null
      samesite: none
      path: /
      domain: null
      httpOnly: false
      partitioned: true # Only for Symfony 6.4 or higher
      split:
        - header
        - payload

    jwt_s:
      lifetime: 0
      samesite: none
      path: /
      domain: null
      httpOnly: true
      partitioned: true # Only for Symfony 6.4 or higher
      split:
        - signature
